### ISSUE TITLE
No connection could be made

### ISSUE THREAD

**Issue by hardikpoojara** [maxteebabs/Laravel-blockchain-api#8]
Hello,

I'm using Laravel 5.2 and i want to get wallet balance into AuthController.
My code is as below 

`Blockchain::getWalletBalance("ec6f1bd3-f9ac-4c02-a096-7eb6a7de32a0", '******')`

I'm getting an error as 
`{
    "status": 400,
    "data": [],
    "messsagge": "file_get_contents(http://localhost:3000/merchant/ec6f1bd3-f9ac-4c02-a096-7eb6a7de32a0/new_address?password=***): failed to open stream: No connection could be made because the target machine actively refused it.\r\n",
    "code": 0
}`

**Comment by maxteebabs** [comment]
Hi Hardik,You need to start the blockchain service locally on your machine.  Please use this link https://github.com/blockchain/service-my-wallet-v3#installation before you can consume the api package    On Tuesday, August 13, 2019, 11:10:16 AM GMT+1, Hardik Poojara <notifications@github.com> wrote:  
 
 
Hello,

I'm using Laravel 5.2 and i want to get wallet balance into AuthController.
My code is as below

Blockchain::getWalletBalance("ec6f1bd3-f9ac-4c02-a096-7eb6a7de32a0", '******')

I'm getting an error as
{ "status": 400, "data": [], "messsagge": "file_get_contents(http://localhost:3000/merchant/ec6f1bd3-f9ac-4c02-a096-7eb6a7de32a0/new_address?password=***): failed to open stream: No connection could be made because the target machine actively refused it.\r\n", "code": 0 }
